POST http://localhost:8080/api/admin/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwMUpGSFhaTlNENjZONTVFSE1OSlM1WUVQUiIsInJvbGUiOiJTajA4IiwiaWF0IjoxNzM0NzA4NjU0LCJleHAiOjE3MzQ3OTUwNTR9.Q_soYYAGPIKhF7Q7kBV2SIjSf3ZwWX0VipHNTerWgy8
Content-Type: application/json

{
  "name": "sjj",
  "account": "2022220976",
  "role": "Js09",
  "telephone": "18345930160"
}
